problems:
  allinitu:
  arglina:
  arglinb:
  arglinc:
  arwhead:
  bdexp:
  beale:
  brkmcc:
  brownal:
  brownbs:
  chnrosnb:
  cliff:
  cosine:
  cube:
  denschna:
  denschnb:
  denschnc:
  denschnd:
  denschne:
  denschnf:
  dixon3dq:
  dqdrtic:
#  dqrtic:
  edensch:
  eigenals:
  eigenb:
  eigenbls:
  engval1:
  engval2:
  errinros:
  expfit:
#  extrosnb:
  fletcbv2:
#  fletcbv3:
#  fletchbv:
  fletchcr:
  genrose:
#  growth:
#  growthls:
solvers:
  GenoSolver:
    options:
      max_iter: 1000
  ScipySolver:
    method: L-BFGS-B
    options:
      maxiter: 1000
#      disp: 101
#  ScipyBFGS:
#    options:
#      maxiter: 1000
#      disp: 101