problems:
single_problems:
  A0ENDNDL: null
  A0ENINDL: null
  A0ENSNDL: null
  A0ESDNDL: null
  A0ESINDL: null
  A0ESSNDL: null
  A0NNDNDL: null
  A0NNDNIL: null
  A0NNDNSL: null
  A0NNSNSL: null
  A0NSDSDL: null
  A0NSDSDS: null
  A0NSDSIL: null
  A0NSDSSL: null
  A0NSSSSL: null
  A2ENDNDL: null
  A2ENINDL: null
  A2ENSNDL: null
  A2ESDNDL: null
  A2ESINDL: null
  A2ESSNDL: null
  A2NNDNDL: null
  A2NNDNIL: null
  A2NNDNSL: null
  A2NNSNSL: null
  A2NSDSDL: null
  A2NSDSIL: null
  A2NSDSSL: null
  A2NSSSSL: null
  A5ENDNDL: null
  A5ENINDL: null
  A5ENSNDL: null
  A5ESDNDL: null
  A5ESINDL: null
  A5ESSNDL: null
  A5NNDNDL: null
  A5NNDNIL: null
  A5NNDNSL: null
  A5NNSNSL: null
  A5NSDSDL: null
  A5NSDSDM: null
  A5NSDSIL: null
  A5NSDSSL: null
  A5NSSNSM: null
  A5NSSSSL: null
  AGG: null
  ALLINQP: null
  ANTWERP: null
  ARGLALE: null
  ARGLBLE: null
  ARGLCLE: null
  AUG2D: null
  AUG2DC: null
  AUG2DCQP: null
  AUG2DQP: null
  AUG3D: null
  AUG3DC: null
  AUG3DCQP: null
  AUG3DQP: null
  AVGASA: null
  AVGASB: null
  AVION2: null
  BDRY2: null
  BIGGSC4: null
  BLOCKQP1: null
  BLOCKQP2: null
  BLOCKQP3: null
  BLOCKQP4: null
  BLOCKQP5: null
  BLOWEYA: null
  BLOWEYB: null
  BLOWEYC: null
  BOOTH: null
  BT3: null
  BTS4: null
  CBS: null
  CLEUVEN2: null
  CLEUVEN3: null
  CLEUVEN4: null
  CLEUVEN5: null
  CLEUVEN6: null
  CLEUVEN7: null
  CMPC1: null
  CMPC10: null
  CMPC11: null
  CMPC12: null
  CMPC13: null
  CMPC14: null
  CMPC15: null
  CMPC16: null
  CMPC2: null
  CMPC3: null
  CMPC4: null
  CMPC5: null
  CMPC6: null
  CMPC7: null
  CMPC8: null
  CMPC9: null
  CONT5-QP: null
  CVXQP1: null
  CVXQP2: null
  CVXQP3: null
  DALE: null
  DEGENLPA: null
  DEGENLPB: null
  DEGENQP: null
  DEGENQPC: null
  DEGTRIDL: null
  DTOC1L: null
  DTOC3: null
  DUAL1: null
  DUAL2: null
  DUAL3: null
  DUAL4: null
  DUALC1: null
  DUALC2: null
  DUALC5: null
  DUALC8: null
  EQC: null
  EXPFITA: null
  EXPFITB: null
  EXPFITC: null
  EXTRASIM: null
  FCCU: null
  FERRISDC: null
  FIVE20B: null
  FIVE20C: null
  GENHS28: null
  GMNCASE1: null
  GMNCASE2: null
  GMNCASE3: null
  GMNCASE4: null
  GOFFIN: null
  GOULDQP1: null
  GOULDQP2: null
  GOULDQP3: null
  HAGER1: null
  HAGER2: null
  HAGER3: null
  HAGER4: null
  HATFLDH: null
  HIE1327D: null
  HIE1372D: null
  HIER13: null
  HIER133A: null
  HIER133D: null
  HIER133E: null
  HIER16: null
  HIER163A: null
  HIER163D: null
  HIMMELBA: null
  HIMMELBI: null
  HIMMELBJ: null
  HONG: null
  HS105: null
  HS112: null
  HS118: null
  HS119: null
  HS21: null
  HS21MOD: null
  HS24: null
  HS268: null
  HS28: null
  HS35: null
  HS35I: null
  HS35MOD: null
  HS36: null
  HS37: null
  HS41: null
  HS44: null
  HS44NEW: null
  HS48: null
  HS49: null
  HS50: null
  HS51: null
  HS52: null
  HS53: null
  HS54: null
  HS55: null
  HS62: null
  HS76: null
  HS76I: null
  HS86: null
  HS9: null
  HUBFIT: null
  HUES-MOD: null
  HUESTIS: null
  HYDROELL: null
  HYDROELM: null
  HYDROELS: null
  JJTABEL3: null
  KSIP: null
  LEUVEN1: null
  LEUVEN2: null
  LEUVEN3: null
  LEUVEN4: null
  LEUVEN5: null
  LEUVEN6: null
  LEUVEN7: null
  LIN: null
  LINCONT: null
  LISWET1: null
  LISWET10: null
  LISWET11: null
  LISWET12: null
  LISWET2: null
  LISWET3: null
  LISWET4: null
  LISWET5: null
  LISWET6: null
  LISWET7: null
  LISWET8: null
  LISWET9: null
  LOADBAL: null
  LOTSCHD: null
  LSQFIT: null
  MAKELA4: null
  MODEL: null
  MOSARQP1: null
  MOSARQP2: null
  MPC1: null
  MPC10: null
  MPC11: null
  MPC12: null
  MPC13: null
  MPC14: null
  MPC15: null
  MPC16: null
  MPC2: null
  MPC3: null
  MPC4: null
  MPC5: null
  MPC6: null
  MPC7: null
  MPC8: null
  MPC9: null
  NASH: null
  NCVXQP1: null
  NCVXQP2: null
  NCVXQP3: null
  NCVXQP4: null
  NCVXQP5: null
  NCVXQP6: null
  NCVXQP7: null
  NCVXQP8: null
  NCVXQP9: null
  NINE12: null
  NINE5D: null
  NINENEW: null
  ODFITS: null
  OET1: null
  OET3: null
  OSORIO: null
  PDE1: null
  PDE2: null
  PENTAGON: null
  PORTFL1: null
  PORTFL2: null
  PORTFL3: null
  PORTFL4: null
  PORTFL6: null
  PORTSNQP: null
  PORTSQP: null
  POWELL20: null
  PRIMAL1: null
  PRIMAL2: null
  PRIMAL3: null
  PRIMAL4: null
  PRIMALC1: null
  PRIMALC2: null
  PRIMALC5: null
  PRIMALC8: null
  PT: null
  QC: null
  QCNEW: null
  QPBAND: null
  QPCBLEND: null
  QPCBOEI1: null
  QPCBOEI2: null
  QPCSTAIR: null
  QPNBAND: null
  QPNBLEND: null
  QPNBOEI1: null
  QPNBOEI2: null
  QPNSTAIR: null
  RDW2D51F: null
  RDW2D51U: null
  RDW2D52B: null
  RDW2D52F: null
  RDW2D52U: null
  READING2: null
  REPEAT: null
  RES: null
  S268: null
  S277-280: null
  SCW1: null
  SCW2: null
  SIMPLLPA: null
  SIMPLLPB: null
  SIPOW1: null
  SIPOW1M: null
  SIPOW2: null
  SIPOW2M: null
  SIPOW3: null
  SIPOW4: null
  SOSQP1: null
  SOSQP2: null
  SSEBLIN: null
  STANCMIN: null
  STATIC3: null
  STCQP1: null
  STCQP2: null
  STNQP1: null
  STNQP2: null
  SUPERSIM: null
  SYNPOP24: null
  TABLE1: null
  TABLE3: null
  TABLE6: null
  TABLE7: null
  TABLE8: null
  TAME: null
  TARGUS: null
  TFI2: null
  TFI3: null
  TOYSARAH: null
  TWO5IN6: null
  TWOD: null
  UBH1: null
  YAO: null
  ZANGWIL3: null
  ZECEVIC2: null
solvers:
  GenoSolver:
    options:
      max_iter: 1000
#      verbose: 10
  ScipySolver:
    method: L-BFGS-B
    options:
      maxiter: 1000
#      disp: 10
  GenoSolverC:
    options:
#      verbosity: 10
      maxiter: 1000
  IpoptSolver:
    options:
      max_iter: 1000