problems:
single_problems:
  10FOLDTR: null
  ACOPP118: null
  ACOPP14: null
  ACOPP30: null
  ACOPP300: null
  ACOPP57: null
  ACOPR118: null
  ACOPR14: null
  ACOPR30: null
  ACOPR300: null
  ACOPR57: null
  AIRCRFTA: null
  ALLINITA: null
  ALLINITC: null
  ALSOTAME: null
  ARGAUSS: null
  ARGTRIG: null
  ARTIF: null
  ARWHDNE: null
  BA-L1: null
  BA-L16: null
  BA-L1SP: null
  BA-L21: null
  BA-L49: null
  BA-L52: null
  BA-L73: null
  BARDNE: null
  BATCH: null
  BDQRTICNE: null
  BDVALUE: null
  BDVALUES: null
  BEALENE: null
  BENNETT5: null
  BIGGS6NE: null
  BOX3NE: null
  BOXBOD: null
  BRAINPC0: null
  BRAINPC1: null
  BRAINPC2: null
  BRAINPC3: null
  BRAINPC4: null
  BRAINPC5: null
  BRAINPC6: null
  BRAINPC7: null
  BRAINPC8: null
  BRAINPC9: null
  BRATU2D: null
  BRATU2DT: null
  BRATU3D: null
  BRIDGEND: null
  BRITGAS: null
  BROWNALE: null
  BROWNBSNE: null
  BROWNDENE: null
  BROYDNBD: null
  BRYBNDNE: null
  BT10: null
  BT11: null
  BT6: null
  BT9: null
  BURKEHAN: null
  C-RELOAD: null
  CAMSHAPE: null
  CANTILVR: null
  CAR2: null
  CATMIX: null
  CB2: null
  CB3: null
  CBRATU2D: null
  CBRATU3D: null
  CERI651A: null
  CERI651B: null
  CERI651C: null
  CERI651D: null
  CERI651E: null
  CHACONN1: null
  CHACONN2: null
  CHAIN: null
  CHAINWOONE: null
  CHANDHEQ: null
  CHANDHEU: null
  CHANNEL: null
  CHEMRCTA: null
  CHEMRCTB: null
  CHNRSBNE: null
  CHNRSNBMNE: null
  CHWIRUT1: null
  CHWIRUT2: null
  CLNLBEAM: null
  CLUSTER: null
  COATINGNE: null
  CONCON: null
  CORKSCRW: null
  COSHFUN: null
  CRESC100: null
  CRESC132: null
  CRESC4: null
  CRESC50: null
  CSFI1: null
  CSFI2: null
  CUBENE: null
  CYCLIC3: null
  CYCLIC3LS: null
  DANIWOOD: null
  DANWOOD: null
  DECONVBNE: null
  DECONVNE: null
  DEMBO7: null
  DENSCHNBNE: null
  DENSCHNCNE: null
  DENSCHNDNE: null
  DENSCHNENE: null
  DENSCHNFNE: null
  DEVGLA1NE: null
  DEVGLA2NE: null
  DIAMON2D: null
  DIAMON3D: null
  DIPIGRI: null
  DIXCHLNG: null
  DIXCHLNV: null
  DMN15102: null
  DMN15103: null
  DMN15332: null
  DMN15333: null
  DMN37142: null
  DMN37143: null
  DNIEPER: null
  DRUGDIS: null
  DRUGDISE: null
  DTOC2: null
  DTOC4: null
  DTOC6: null
  ECKERLE4: null
  EG3: null
  EGGCRATENE: null
  EIGENAU: null
  EIGENB: null
  EIGENC: null
  ELATTAR: null
  ELATVIDUNE: null
  ELEC: null
  ENGVAL2NE: null
  ENSO: null
  ERRINBAR: null
  ERRINROSNE: null
  ERRINRSMNE: null
  EXP2NE: null
  EXPFITNE: null
  EXTROSNBNE: null
  FBRAIN: null
  FBRAIN2: null
  FBRAIN2NE: null
  FBRAIN3: null
  FBRAINNE: null
  FEEDLOC: null
  FLETCHER: null
  FLT: null
  FREURONE: null
  GASOIL: null
  GAUSS1: null
  GAUSS2: null
  GAUSS3: null
  GAUSSELM: null
  GBRAIN: null
  GENROSEBNE: null
  GENROSENE: null
  GIGOMEZ2: null
  GIGOMEZ3: null
  GLIDER: null
  GPP: null
  GROWTH: null
  GULFNE: null
  HAHN1: null
  HALDMADS: null
  HATFLDANE: null
  HATFLDBNE: null
  HATFLDCNE: null
  HATFLDDNE: null
  HATFLDENE: null
  HATFLDF: null
  HATFLDFLNE: null
  HATFLDG: null
  HEART6: null
  HEART8: null
  HELIXNE: null
  HELSBY: null
  HIMMELBFNE: null
  HIMMELBK: null
  HS100: null
  HS100LNP: null
  HS100MOD: null
  HS101: null
  HS102: null
  HS103: null
  HS104: null
  HS107: null
  HS109: null
  HS111: null
  HS111LNP: null
  HS114: null
  HS13: null
  HS1NE: null
  HS25NE: null
  HS26: null
  HS2NE: null
  HS32: null
  HS34: null
  HS39: null
  HS40: null
  HS46: null
  HS47: null
  HS56: null
  HS60: null
  HS64: null
  HS66: null
  HS67: null
  HS68: null
  HS69: null
  HS7: null
  HS71: null
  HS72: null
  HS73: null
  HS74: null
  HS75: null
  HS77: null
  HS78: null
  HS79: null
  HS80: null
  HS81: null
  HS85: null
  HS87: null
  HS88: null
  HS89: null
  HS90: null
  HS91: null
  HS92: null
  HS93: null
  HS99: null
  HS99EXP: null
  HVYCRASH: null
  HYDCAR20: null
  HYDCAR6: null
  INTEGREQ: null
  INTEQNE: null
  JENSMPNE: null
  JUDGENE: null
  KIRBY2: null
  KOEBHELBNE: null
  KOWOSBNE: null
  KSS: null
  KTMODEL: null
  LAKES: null
  LANCZOS1: null
  LANCZOS2: null
  LANCZOS3: null
  LAUNCH: null
  LCH: null
  LEAKNET: null
  LEVYMONE: null
  LEVYMONE10: null
  LEVYMONE5: null
  LEVYMONE6: null
  LEVYMONE7: null
  LEVYMONE8: null
  LEVYMONE9: null
  LEWISPOL: null
  LIARWHDNE: null
  LINVERSENE: null
  LOBSTERZ: null
  LSC1: null
  LSC2: null
  LUBRIF: null
  LUBRIFC: null
  LUKSAN11: null
  LUKSAN12: null
  LUKSAN13: null
  LUKSAN14: null
  LUKSAN15: null
  LUKSAN16: null
  LUKSAN17: null
  LUKSAN21: null
  LUKSAN22: null
  LUKVLE1: null
  LUKVLE11: null
  LUKVLE2: null
  LUKVLE3: null
  LUKVLE4: null
  LUKVLE5: null
  LUKVLE6: null
  LUKVLE7: null
  LUKVLE8: null
  LUKVLE9: null
  LUKVLI1: null
  LUKVLI11: null
  LUKVLI2: null
  LUKVLI3: null
  LUKVLI4: null
  LUKVLI5: null
  LUKVLI6: null
  LUKVLI7: null
  LUKVLI8: null
  LUKVLI9: null
  MADSEN: null
  MANCINONE: null
  MANNE: null
  MARINE: null
  MATRIX2: null
  MCONCON: null
  MESH: null
  METHANB8: null
  METHANL8: null
  METHANOL: null
  MEYER3NE: null
  MGH09: null
  MGH10: null
  MGH10S: null
  MGH17: null
  MGH17S: null
  MGH17SLS: null
  MINMAXBD: null
  MISRA1A: null
  MISRA1B: null
  MISRA1C: null
  MISRA1D: null
  MNISTS0: null
  MNISTS5: null
  MODBEALENE: null
  MOREBVNE: null
  MRIBASIS: null
  MUONSINE: null
  NELSON: null
  NET1: null
  NET2: null
  NET3: null
  NET4: null
  NONDIANE: null
  NONMSQRTNE: null
  NONSCOMPNE: null
  NYSTROM5: null
  OET2: null
  OET4: null
  OET6: null
  OET7: null
  ORBIT2: null
  ORTHRDM2: null
  ORTHRDS2: null
  ORTHREGD: null
  ORTHREGE: null
  ORTHREGF: null
  ORTHRGDM: null
  ORTHRGDS: null
  OSBORNE1: null
  OSBORNE2: null
  OSCIGRNE: null
  OSCIPANE: null
  PALMER1ANE: null
  PALMER1BNE: null
  PALMER1ENE: null
  PALMER1NE: null
  PALMER2ANE: null
  PALMER2BNE: null
  PALMER2ENE: null
  PALMER2NE: null
  PALMER3ANE: null
  PALMER3BNE: null
  PALMER3ENE: null
  PALMER3NE: null
  PALMER4ANE: null
  PALMER4BNE: null
  PALMER4ENE: null
  PALMER4NE: null
  PALMER5ANE: null
  PALMER5BNE: null
  PALMER5ENE: null
  PALMER6ANE: null
  PALMER6ENE: null
  PALMER7ANE: null
  PALMER7ENE: null
  PALMER8ANE: null
  PALMER8ENE: null
  PENLT1NE: null
  PENLT2NE: null
  PFIT1: null
  PFIT2: null
  PFIT3: null
  PFIT4: null
  PINENE: null
  POLAK1: null
  POLAK2: null
  POLAK3: null
  POLAK5: null
  POLAK6: null
  POLYGEVEN: null
  POLYGODD: null
  POLYGON: null
  POROUS1: null
  POROUS2: null
  POWELLBS: null
  POWELLSE: null
  POWELLSQ: null
  POWERSUMNE: null
  PRICE3NE: null
  PRICE4NE: null
  QINGNE: null
  RAT42: null
  RAT43: null
  READING1: null
  READING3: null
  READING4: null
  READING5: null
  READING6: null
  READING7: null
  READING8: null
  READING9: null
  RECIPE: null
  RK23: null
  ROBOT: null
  ROBOTARM: null
  ROCKET: null
  ROSZMAN1: null
  RSNBRNE: null
  S308NE: null
  S365: null
  S365MOD: null
  SANTA: null
  SARO: null
  SAROMM: null
  SAWPATH: null
  SBRYBNDNE: null
  SEMICN2U: null
  SEMICON1: null
  SEMICON2: null
  SINVALNE: null
  SNAKE: null
  SPECANNE: null
  SPIN: null
  SPIN2: null
  SPIN2OP: null
  SPINOP: null
  SPIRAL: null
  SREADIN3: null
  SROSENBRNE: null
  SSBRYBNDNE: null
  SSINE: null
  SSNLBEAM: null
  STEERING: null
  STREGNE: null
  STRTCHDVNE: null
  SVANBERG: null
  SYNTHES1: null
  SYNTHES2: null
  SYNTHES3: null
  TAX13322: null
  TAX213322: null
  TAX53322: null
  TAXR13322: null
  TAXR213322: null
  TAXR53322: null
  TENBARS1: null
  TENBARS2: null
  TENBARS3: null
  TENBARS4: null
  TFI1: null
  THURBER: null
  TQUARTICNE: null
  TRAINH: null
  TRIGGER: null
  TRIGON1NE: null
  TRIGON2NE: null
  TRIMLOSS: null
  TRO11X3: null
  TRO21X5: null
  TRO3X3: null
  TRO41X9: null
  TRO4X4: null
  TRO5X5: null
  TRO6X2: null
  TWIRIBG1: null
  TWIRIMD1: null
  TWIRISM1: null
  TWOBARS: null
  VANDANIUMS: null
  VANDERM1: null
  VANDERM2: null
  VANDERM3: null
  VANDERM4: null
  VARDIMNE: null
  VESUVIA: null
  VESUVIO: null
  VESUVIOU: null
  VIBRBEAMNE: null
  WATSONNE: null
  WAYSEA1NE: null
  WAYSEA2NE: null
  WEEDSNE: null
  WOMFLET: null
  WOODSNE: null
  YATP1CNE: null
  YATP1NE: null
  YATP2CNE: null
  YATP2SQ: null
  YFITNE: null
  YORKNET: null
  ZAMB2: null
  ZAMB2-10: null
  ZAMB2-11: null
  ZAMB2-8: null
  ZAMB2-9: null
  ZIGZAG: null
solvers:
  GenoSolver:
    options:
      max_iter: 1000
#      verbose: 10
  ScipySolver:
    method: L-BFGS-B
    options:
      maxiter: 1000
#      disp: 10
  GenoSolverC:
    options:
#      verbosity: 10
      maxiter: 1000
  IpoptSolver:
    options:
      max_iter: 1000