problems:
single_problems:
  A4X12: null
  AIRPORT: null
  ALJAZZAF: null
  BROYDN3D: null
  BT1: null
  BT12: null
  BT13: null
  BT2: null
  BT4: null
  BT5: null
  BT7: null
  BT8: null
  BYRDSPHR: null
  CATENA: null
  CATENARY: null
  CHARDIS1: null
  CONGIGMZ: null
  CONT6-QQ: null
  COOLHANS: null
  CORE1: null
  CORE2: null
  CYCLOOCF: null
  CYCLOOCT: null
  DECONVC: null
  DEMYMALO: null
  DISC2: null
  DISCS: null
  DITTERT: null
  DRCAVTY1: null
  DRCAVTY2: null
  DRCAVTY3: null
  DTOC1NA: null
  DTOC1NB: null
  DTOC1NC: null
  DTOC1ND: null
  DTOC5: null
  EIGENA2: null
  EIGENACO: null
  EIGENB2: null
  EIGENBCO: null
  EIGENC2: null
  EIGENCCO: null
  EIGMAXA: null
  EIGMAXB: null
  EIGMAXC: null
  EIGMINA: null
  EIGMINB: null
  EIGMINC: null
  FLOSP2HH: null
  FLOSP2HL: null
  FLOSP2HM: null
  FLOSP2TH: null
  FLOSP2TL: null
  FLOSP2TM: null
  GIGOMEZ1: null
  GILBERT: null
  GOTTFR: null
  GROUPING: null
  HADAMARD: null
  HAIFAL: null
  HAIFAM: null
  HAIFAS: null
  HANGING: null
  HET-Z: null
  HIMMELBC: null
  HIMMELBD: null
  HIMMELBE: null
  HIMMELP2: null
  HIMMELP3: null
  HIMMELP4: null
  HIMMELP5: null
  HIMMELP6: null
  HS10: null
  HS106: null
  HS108: null
  HS11: null
  HS113: null
  HS116: null
  HS117: null
  HS12: null
  HS14: null
  HS15: null
  HS16: null
  HS17: null
  HS18: null
  HS19: null
  HS20: null
  HS22: null
  HS23: null
  HS27: null
  HS29: null
  HS30: null
  HS31: null
  HS33: null
  HS42: null
  HS43: null
  HS57: null
  HS59: null
  HS6: null
  HS61: null
  HS63: null
  HS65: null
  HS70: null
  HS8: null
  HS83: null
  HS84: null
  HS95: null
  HS96: null
  HS97: null
  HS98: null
  HYPCIR: null
  JANNSON3: null
  JANNSON4: null
  JUNKTURN: null
  KISSING: null
  KISSING2: null
  KIWCRESC: null
  LHAIFAM: null
  LIPPERT1: null
  LIPPERT2: null
  LOOTSMA: null
  LUKVLE10: null
  LUKVLE12: null
  LUKVLE13: null
  LUKVLE14: null
  LUKVLE15: null
  LUKVLE16: null
  LUKVLE17: null
  LUKVLE18: null
  LUKVLI10: null
  LUKVLI12: null
  LUKVLI13: null
  LUKVLI14: null
  LUKVLI15: null
  LUKVLI16: null
  LUKVLI17: null
  LUKVLI18: null
  MADSSCHJ: null
  MAKELA1: null
  MAKELA2: null
  MAKELA3: null
  MARATOS: null
  MIFFLIN1: null
  MIFFLIN2: null
  MINC44: null
  MINMAXRB: null
  MINPERM: null
  MISTAKE: null
  MSQRTA: null
  MSQRTB: null
  MSS1: null
  MSS2: null
  MSS3: null
  MWRIGHT: null
  NGONE: null
  NUFFIELD: null
  OET5: null
  OPTCDEG2: null
  OPTCDEG3: null
  OPTCNTRL: null
  OPTCTRL3: null
  OPTCTRL6: null
  OPTMASS: null
  OPTPRLOC: null
  ORTHREGA: null
  ORTHREGB: null
  ORTHREGC: null
  POLAK4: null
  PRODPL0: null
  PRODPL1: null
  QR3D: null
  QR3DBD: null
  ROSENMMX: null
  ROSEPETAL: null
  ROSEPETAL2: null
  ROTDISC: null
  S316-322: null
  SINROSNB: null
  SMMPSF: null
  SPMSQRT: null
  SSEBNLN: null
  SWOPF: null
  TRAINF: null
  TRUSPYR1: null
  TRUSPYR2: null
  TRY-B: null
  UBH5: null
  WACHBIEG: null
  ZECEVIC3: null
  ZECEVIC4: null
  ZY2: null
solvers:
  GenoSolver:
    options:
      max_iter: 1000
#      verbose: 10
  ScipySolver:
    method: L-BFGS-B
    options:
      maxiter: 1000
#      disp: 10
  GenoSolverC:
    options:
#      verbosity: 10
      maxiter: 1000
  IpoptSolver:
    options:
      max_iter: 1000